name: myenv
channels:
  - defaults
  - pytorch     # Include if using PyTorch to ensure compatible installation
dependencies:
  - python=3.9
  - numpy=1.21
  - pandas
  - fastapi
  - uvicorn
  - python-multipart
  - torch       # PyTorch
  - sentence-transformers
  - beautifulsoup4
  - spacy
  - pydantic
  - typing-extensions
  - python-dotenv
